### ISSUE TITLE
Can I use these exercises when I do some Scala training to other companies?

### ISSUE THREAD

**Issue by freewind** [cwmyers/FunctionalTraining#6]
Hi Chris,

I will do some Scala functional programming training to some companies, I wonder is it allowed to use these excellent exercises during the training?

PS: I will reference this repo when training, and the copyright will belong to you.

**Comment by cwmyers** [comment]
Of course you can! Let me know how it goes and if there is anything I can improve!




Cheers

Chris



—

**Comment by freewind** [comment]
Thanks very much, Chris. I will feedback when it goes
